# Generated by Django 2.2.12 on 2020-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0002_auto_20200526_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitprogress',
            name='unit_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='microcontentprogress',
            name='mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='microcontentprogress',
            name='micro_content_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unitprogress',
            name='next_micro_content_id',
            field=models.IntegerField(default=0),
        ),
    ]
