# Generated by Django 2.2.12 on 2020-05-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0003_auto_20200527_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitprogress',
            name='next_micro_content_id',
        ),
    ]
