# Generated by Django 2.2.12 on 2020-05-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0004_next_micro_content_id_DELETED'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microcontentprogress',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='microcontentprogress',
            name='micro_content_id',
        ),
        migrations.RemoveField(
            model_name='unitprogress',
            name='unit_id',
        ),
        migrations.AlterField(
            model_name='microcontentprogress',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitprogress',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
